packages:
  - .
  - packages/*

catalog:
  '@fontsource/roboto': 5.2.8
  '@rotki/ui-library': 2.7.0
  '@types/braintree-web': 3.96.17
  '@unhead/vue': 2.0.19
  '@vitejs/plugin-vue': 6.0.1
  '@vue/tsconfig': 0.7.0
  '@vueuse/core': 13.9.0
  autoprefixer: 10.4.21
  braintree-web: 3.132.0
  postcss: 8.5.6
  tailwindcss: 3.4.17
  typescript: 5.9.3
  vite: 7.1.11
  vite-ssg: 28.2.2
  vue: 3.5.22
  vue-tsc: 3.1.1
  zod: 3.25.76
