packages:
  - .
  - packages/*

catalog:
  vue: 3.5.21
  typescript: 5.9.2
  vite: 7.1.11
  '@vueuse/core': 13.9.0
  zod: 3.25.76
  braintree-web: 3.129.0
  '@types/braintree-web': 3.96.17
  tailwindcss: 3.4.17
  postcss: 8.5.6
  autoprefixer: 10.4.21
  vue-tsc: 3.0.7
  '@vitejs/plugin-vue': 6.0.1
  '@vue/tsconfig': 0.7.0
  vite-ssg: 28.1.0
  '@rotki/ui-library': 2.7.0
  '@unhead/vue': 2.0.14
  '@fontsource/roboto': 5.2.7
