packages:
  - .
  - packages/*

catalog:
  '@fontsource/roboto': 5.2.8
  '@rotki/ui-library': 2.8.1
  '@types/braintree-web': 3.96.17
  '@types/node': 22.19.1
  '@tsconfig/node22': 22.0.3
  '@unhead/vue': 2.0.19
  '@vitejs/plugin-vue': 6.0.1
  '@vue/tsconfig': 0.7.0
  '@vueuse/core': 14.0.0
  '@vueuse/math': 14.0.0
  '@vueuse/nuxt': 14.0.0
  '@vueuse/shared': 14.0.0
  autoprefixer: 10.4.22
  braintree-web: 3.133.0
  postcss: 8.5.6
  tailwindcss: 3.4.17
  typescript: 5.9.3
  vite: 7.2.2
  vite-ssg: 28.2.2
  vue: 3.5.24
  vue-tsc: 3.1.3
  zod: 3.25.76
