version: '2'

run:
  timeout: 5m

formatters:
  enable:
    - gofumpt

linters:
  enable:
    - bodyclose
    - copyloopvar
    - errcheck
    - errorlint
    - exhaustive
    - gocritic
    - gosec
    - govet
    - ineffassign
    - misspell
    - nilerr
    - noctx
    - prealloc
    - revive
    - sloglint
    - staticcheck
    - testifylint
    - unconvert
    - unparam
    - unused
    - usestdlibvars
    - wastedassign

  settings:
    govet:
      enable-all: true
      disable:
        - fieldalignment
    errcheck:
      check-type-assertions: false
      check-blank: false
    revive:
      rules:
        - name: blank-imports
        - name: context-as-argument
        - name: dot-imports
        - name: error-naming
        - name: error-return
        - name: error-strings
        - name: exported
        - name: increment-decrement
        - name: indent-error-flow
        - name: package-comments
        - name: range
        - name: receiver-naming
        - name: redefines-builtin-id
        - name: time-naming
        - name: unexported-return
        - name: unused-parameter
        - name: var-declaration
        - name: var-naming
    gosec: {}
    errorlint:
      errorf: true
      asserts: true
      comparison: true
    exhaustive:
      default-signifies-exhaustive: true

  exclusions:
    generated: lax
    paths:
      - vendor
