<template>
  <page>
    <template #title> Terms Of Service </template>

    <paragraph>
      These terms and conditions outline the rules and regulations for the use
      of rotki.com Website and all services offered in the Premium Rotki
      subscription.
    </paragraph>

    <paragraph>
      By accessing this website, using the Rotki application or using the
      Premium subscription we assume you accept these terms and conditions in
      full. Do not continue to use rotki.com's website if you do not accept all
      of the terms and conditions stated on this page.
    </paragraph>

    <paragraph>
      The following terminology applies to these Terms and Conditions, Privacy
      Statement and Disclaimer Notice and any or all Agreements: “Client”, “You”
      and “Your” refers to you, the person accessing this website and accepting
      the Company’s terms and conditions. “The Company”, “Ourselves”, “We”,
      “Our” and “Us”, refers to our Company. “Party”, “Parties”, or “Us”, refers
      to both the Client and ourselves, or either the Client or ourselves. All
      terms refer to the offer, acceptance and consideration of payment
      necessary to undertake the process of our assistance to the Client in the
      most appropriate manner, whether by formal meetings of a fixed duration,
      or any other means, for the express purpose of meeting the Client’s needs
      in respect of provision of the Company’s stated services/products, in
      accordance with and subject to, prevailing law of . Any use of the above
      terminology or other words in the singular, plural, capitalisation and/or
      he/she or they, are taken as interchangeable and therefore as referring to
      same.
    </paragraph>

    <heading> Service Terms </heading>

    <paragraph>
      ROTKI'S SERVICE IS INTENDED ONLY TO IMPORT, DISPLAY, STORE, AND GENERATE
      REPORTS AND STATISTICS FROM CRYPTOCURRENCY TRANSACTION DATA AND OTHER
      ASSETS. YOU, AS THE USER OF THE SERVICE, ARE RESPONSIBLE FOR THE
      TRANSACTION DATA IMPORTED, STORED, AND ANALYZED BY THE SERVICE. IF
      INACCURATE OR INCOMPLETE TRANSACTION DATA IS PROVIDED TO THE SERVICE, THE
      REPORTS GENERATED BY THE SERVICE WILL ALSO BE INACCURATE OR INCOMPLETE.
    </paragraph>

    <paragraph>
      ROTKI DOES NOT PROVIDE TAX OR LEGAL ADVICE THROUGH THE SERVICE AND THE
      SERVICE IS NOT INTENDED TO BE A SUBSTITUTE FOR PROFESSIONAL TAX OR LEGAL
      ADVICE OR FOR YOUR OWN DILIGENCE IN ENSURING THE ACCURACY OF ANY AND ALL
      INFORMATION YOU SUBMIT TO TAX AUTHORITIES. IT IS YOUR RESPONSIBILITY TO
      PRESENT YOUR TRANSACTION DATA AND ANY REPORTS GENERATED BY THE SERVICE TO
      YOUR TAX OR LEGAL ADVISORS FOR REVIEW. ALWAYS SEEK THE ADVICE OF YOUR
      ACCOUNTANTS, ATTORNEYS, OR OTHER QUALIFIED TAX ADVISORS WITH ANY QUESTIONS
      YOU MAY HAVE REGARDING YOUR TAX LIABILITY. NEVER DISREGARD PROFESSIONAL
      TAX OR LEGAL ADVICE OR DELAY IN SEEKING IT BECAUSE OF SOMETHING YOU HAVE
      READ OR BEEN PROVIDED FROM THE SERVICE.
    </paragraph>

    <paragraph>
      THE SERVICE IS NOT INTENDED FOR CONTINUOUS MONITORING OF TRANSACTION DATA
      OR FOR AUTOMATIC TRANSMISSION OF YOUR TRANSACTION DATA OR ANY REPORTS OR
      SAMPLE FORMS GENERATED BY THE SERVICE TO ANY TAX AUTHORITY. YOU CANNOT
      SUBMIT PAYMENT TO ANY TAX AUTHORITY THROUGH THE SERVICE, AND WE ARE NOT
      RESPONSIBLE FOR ANY PAYMENT OR NON-PAYMENT OF TAXES BY YOU.
    </paragraph>

    <heading> Cookies </heading>

    <paragraph>
      We employ the use of cookies. By using rotki's website you consent to the
      use of cookies in accordance with its
      <external-link same-tab text="privacy policy" url="/privacy-policy" />.
    </paragraph>

    <paragraph>
      Most of the modern day interactive web sites use cookies to enable us to
      retrieve user details for each visit. Cookies are used in some areas of
      our site to enable the functionality of this area and ease of use for
      those people visiting.
    </paragraph>

    <heading> License </heading>

    <paragraph>
      Unless otherwise stated, rotki.com and/or it’s licensors own the
      intellectual property rights for all material on the website. All
      intellectual property rights are reserved. You may view and/or print pages
      from it for your own personal use subject to restrictions set in these
      terms and conditions.
    </paragraph>

    <paragraph> You must not: </paragraph>

    <paragraph>
      <ul :class="$style.list">
        <li>Republish material from https://rotki.com</li>
        <li>Sell, rent or sub-license material from https://rotki.com</li>
        <li>Reproduce, duplicate or copy material from https://rotki.com</li>
      </ul>
    </paragraph>

    <paragraph>
      Redistribute content from the website (unless content is specifically made
      for redistribution).
    </paragraph>

    <heading> Payment </heading>

    <paragraph>
      Access to some features of the Service requires you to pay fees. Before
      you pay any fees, you will have an opportunity to review and accept the
      fees that you will be charged. All fees are payable in advance and
      non-refundable, to the fullest extent permitted under applicable law. If
      Rotki changes the fees for the Service, including by adding additional
      fees or charges, you will be provided with an advance notice of those
      changes. If you do not accept the changes, Rotki may discontinue providing
      the Service to you. Rotki will charge the payment method you specify at
      the time of purchase. You authorize Rotki to charge all sums as described
      in these Terms, for the Service you select, to that payment method. The
      Service may include functionality for activating, updating or canceling
      recurring payments for periodic charges. If you activate or update
      recurring payments through the Service, you authorize Rotki to
      periodically charge, on a going-forward basis and until cancellation of
      either the recurring payments or your account, all accrued sums on or
      before the payment due date for the accrued sums. If you use the Service
      to update or cancel any existing authorized one-time or recurring payment,
      it may take several business days for the update or cancellation to take
      effect.
    </paragraph>

    <heading> Iframes </heading>

    <paragraph>
      Without prior approval and express written permission, you may not create
      frames around our Web pages or use other techniques that alter in any way
      the visual presentation or appearance of our Web site.
    </paragraph>

    <heading> Reservation of Rights </heading>

    <paragraph>
      We reserve the right at any time and in our sole discretion to request
      that you remove all links or any particular link to our Web site. You
      agree to immediately remove all links to our Web site upon such request.
      We also reserve the right to amend these terms and conditions and its
      linking policy at any time. By continuing to link to our Web site, you
      agree to be bound to and abide by these linking terms and conditions.
    </paragraph>

    <heading> Removal of links from our website </heading>

    <paragraph>
      If you find any link on our Web site or any linked web site objectionable
      for any reason, you may contact us about this. We will consider requests
      to remove links but will have no obligation to do so or to respond
      directly to you.
    </paragraph>

    <paragraph>
      Whilst we endeavour to ensure that the information on this website is
      correct, we do not warrant its completeness or accuracy; nor do we commit
      to ensuring that the website remains available or that the material on the
      website is kept up to date.
    </paragraph>

    <heading> Prohibited Conduct </heading>

    <paragraph> BY USING THE SERVICE YOU AGREE NOT TO: </paragraph>

    <paragraph>
      use or access the Service (a) from a jurisdiction where such use or access
      is not authorized, (b) for any illegal purpose, or (c) in violation of any
      local, state, national, or international law;conduct activities that may
      be harmful to others or that could damage Rotki’s reputation;
    </paragraph>

    <paragraph>
      violate, or encourage others to violate, any right of a third party,
      including by infringing or misappropriating any third party intellectual
      property right, or disclosing personal information about another person;
    </paragraph>

    <paragraph>
      post, upload, or distribute marketing or advertising links or content, or
      any User Content or other content that is unlawful, defamatory, libelous,
      inaccurate, or that a reasonable person could deem to be objectionable,
      profane, indecent, pornographic, harassing, threatening, embarrassing,
      hateful, or otherwise inappropriate;
    </paragraph>

    <paragraph>
      use scrapers, robots, or other data gathering devices on or through the
      Service, or frame or otherwise provide the Service to third parties
      without Rotki’s permission;
    </paragraph>

    <paragraph>
      interfere with security-related features of the Service, including by: (a)
      disabling or circumventing features that prevent or limit use or copying
      of any content; or (b) reverse engineering, decompiling, or otherwise
      attempting to discover the source code of any portion of the Service,
      except to the extent that such activity is expressly permitted by
      applicable law notwithstanding this restriction;
    </paragraph>

    <paragraph>
      interfere with the operation of the Service or any user’s enjoyment of the
      Service, including by: (a) uploading or otherwise disseminating any virus,
      adware, spyware, worm, or other malicious code; (b) making any unsolicited
      offer or advertisement to another user of the Service; (c) attempting to
      collect personal information, including without limitation Transaction
      Data or other health information, about another user or third party
      without their consent; or (d) interfering with or disrupting any network,
      equipment, or server connected to or used to provide the Service, or
      violating any regulation, policy, or procedure of any such network,
      equipment, or server;
    </paragraph>

    <paragraph>
      perform any fraudulent activity including impersonating any person or
      entity, claiming a false affiliation, accessing any other Service or
      account without permission, or falsifying your account registration
      information;
    </paragraph>

    <paragraph>
      modify, translate, or create derivative works, adaptations or compilations
      of, or based on, the Service or part thereof, or use, copy or reproduce
      the Service or any part thereof other than as expressly permitted in these
      Terms;
    </paragraph>

    <paragraph>
      assign, sublicense, lease, sell, grant a security interest in, or
      otherwise transfer the access granted under these Terms or any Materials
      or any right or ability to view, access, or use any Material; or
    </paragraph>

    <paragraph>
      attempt to do any of the acts described in this Section, or assist or
      permit any person in engaging in any of the acts described in this
      Section.
    </paragraph>

    <heading>
      Termination of Use; Discontinuation and Modification of the Service
    </heading>

    <paragraph>
      You may terminate your account at any time by following the procedures
      detailed on Rotki website or contacting customer service at
      support@rotki.com. If you violate any provision of these Terms, your
      permission from us to use the Service will terminate automatically. In
      addition, Rotki may in its sole discretion terminate your user account on
      the Service or suspend or terminate your access to the Service at any time
      if you violate any provision of these Terms, if we no longer provide any
      part of the Services or for any other reason, with or without notice. We
      also reserve the right to modify or discontinue the Service at any time
      (including by limiting or discontinuing certain features of the Service),
      temporarily or permanently, without notice to you. To the fullest extent
      permitted under applicable law, we will have no liability on account of
      any change to the Service or any suspension or termination of your access
      to or use of the Service, provided that if Rotki ceases to operate the
      Service and terminates your access to the Service accordingly, then you
      will be entitled to a pro-rated refund of any prepaid fees that you have
      paid to Rotki for use of the Service. Upon the termination of your account
      or this agreement for any reason, Rotki may at its option delete any data
      associated with your account.
    </paragraph>

    <heading> Modifications to the Terms of Service </heading>

    <paragraph>
      We reserve the right, at our discretion, to change these Terms on a
      going-forward basis at any time. Please check these Terms periodically for
      changes. If a change to these Terms materially modifies your rights or
      obligations, we will notify you of the modified Terms by email to the
      address you provided in your user profile and/or in a notification in the
      Service or on our website. Material modifications will be effective upon
      your acceptance of such modified Terms or upon your continued use of the
      Service after we send or post our notification of the changes, whichever
      is earlier. Immaterial modifications are effective upon publication.
      Disputes arising under these Terms will be resolved in accordance with the
      version of these Terms that was in effect at the time the dispute arose.
      Your sole and exclusive remedy if you do not agree with any modification
      to these Terms is to cancel your account. You may not amend or modify
      these Terms under any circumstances.
    </paragraph>

    <heading> Indemnity </heading>

    <paragraph>
      To the fullest extent permitted under applicable law, you are responsible
      for your use of the Service, and you will indemnify, hold harmless, and,
      if so directed by Rotki, defend Rotki and its officers, directors,
      employees, consultants, affiliates, subsidiaries and agents (together, the
      “Rotki Entities”) from and against every claim, liability, damage, loss,
      and expense, including reasonable attorneys' fees and costs, arising out
      of or in any way connected with: (a) your access to, use of, or alleged
      use of, the Service; (b) your violation of any portion of these Terms, any
      representation, warranty, or agreement referenced in these Terms, or any
      applicable law or regulation; (c) your violation of any third-party right,
      including any intellectual property right or publicity, confidentiality,
      other property, or privacy right; (d) any dispute or issue between you and
      any third party; and (e) all claims arising from or alleging fraud,
      intentional misconduct, criminal acts, or gross negligence committed by
      you. To the fullest extent permitted under applicable law, we reserve the
      right, at our own expense, to assume the exclusive defense and control of
      any matter otherwise subject to indemnification by you (without limiting
      your indemnification obligations with respect to that matter), and in that
      case, you agree to cooperate with our defense of that claim.
    </paragraph>

    <heading> Disclaimer </heading>

    <paragraph>
      THE SERVICE AND ALL INFORMATION, MATERIALS AND CONTENT AVAILABLE THROUGH
      THE SERVICE ARE PROVIDED “AS IS” AND ON AN “AS AVAILABLE” BASIS, WITHOUT
      WARRANTY OR CONDITION OF ANY KIND, EITHER EXPRESS OR IMPLIED. THE ROTKI
      ENTITIES DISCLAIM ALL WARRANTIES OF ANY KIND, WHETHER EXPRESS OR IMPLIED,
      RELATING TO THE SERVICE, ALL INFORMATION, MATERIALS AND CONTENT AVAILABLE
      THROUGH THE SERVICE, AND ANY SOFTWARE OR HARDWARE ASSOCIATED OR USED WITH
      THE SERVICE, OR THE AVAILABILITY OF ANY OF THE FOREGOING, INCLUDING: (A)
      ANY IMPLIED WARRANTY OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE,
      TITLE, QUIET ENJOYMENT, OR NON-INFRINGEMENT; (B) ANY WARRANTY ARISING OUT
      OF COURSE OF DEALING, USAGE, OR TRADE; AND (C) ANY WARRANTY AS TO WHETHER
      THE TRANSACTION DATA, REPORTS, SAMPLE FORMS, OR OTHER INFORMATION
      AVAILABLE ON OR TRANSMITTED BY THE SERVICE ARE TRUE, COMPLETE OR ACCURATE.
      YOU SPECIFICALLY ACKNOWLEDGE AND AGREE THAT ROTKI IS NOT RESPONSIBLE FOR
      ANY TAX, LEGAL OR OTHER DECISIONS MADE BY YOU OR YOUR TAX OR LEGAL
      ADVISORS BASED UPON INFORMATION COLLECTED, TRANSMITTED, DISPLAYED, OR
      OTHERWISE PROVIDED TO YOU BY OR ON THE SERVICE, WHETHER SUCH INFORMATION
      IS ACCURATE OR INACCURATE. THE ROTKI ENTITIES DO NOT WARRANT THAT THE
      SERVICE OR ANY PORTION OF THE SERVICE, OR ANY MATERIALS OR CONTENT OFFERED
      THROUGH THE SERVICE, WILL BE UNINTERRUPTED, SECURE, OR FREE OF ERRORS,
      VIRUSES, OR OTHER HARMFUL COMPONENTS, AND DO NOT WARRANT THAT ANY OF THOSE
      ISSUES WILL BE CORRECTED.
    </paragraph>

    <paragraph>
      NO ADVICE OR INFORMATION, WHETHER ORAL OR WRITTEN, OBTAINED BY YOU FROM
      THE SERVICE OR ANY MATERIALS OR CONTENT AVAILABLE THROUGH THE SERVICE WILL
      CREATE ANY WARRANTY REGARDING ANY OF THE ROTKI ENTITIES OR THE SERVICE
      THAT IS NOT EXPRESSLY STATED IN THESE TERMS. YOU ASSUME ALL RISK FOR ANY
      LOSS OR DAMAGE THAT MAY RESULT FROM YOUR USE OF OR ACCESS TO THE SERVICE,
      YOUR DEALING WITH ANY OTHER SERVICE USER, AND ANY MATERIALS OR CONTENT
      AVAILABLE THROUGH THE SERVICE. YOU UNDERSTAND AND AGREE THAT YOU USE THE
      SERVICE, AND USE, ACCESS, DOWNLOAD, OR OTHERWISE OBTAIN MATERIALS OR
      CONTENT THROUGH THE SERVICE AND ANY ASSOCIATED SITES OR SERVICES, AT YOUR
      OWN DISCRETION AND RISK, AND THAT YOU ARE SOLELY RESPONSIBLE FOR ANY
      DAMAGE TO YOUR PERSON, PROPERTY (INCLUDING YOUR COMPUTER SYSTEM OR MOBILE
      DEVICE USED IN CONNECTION WITH THE SERVICE), OR THE LOSS OF DATA THAT
      RESULTS FROM THE USE OF THE SERVICE OR THE DOWNLOAD OR USE OF THAT
      MATERIAL OR CONTENT. THE ABOVE PARAGRAPHS APPLY TO THE FULLEST EXTENT
      PERMITTED UNDER APPLICABLE LAW. SOME JURISDICTIONS MAY PROHIBIT A
      DISCLAIMER OF WARRANTIES, IN PARTICULAR A DISCLAIMER OF WARRANTIES
      PROVIDED OR IMPLIED BY LAW, AND YOU MAY HAVE OTHER RIGHTS THAT VARY FROM
      JURISDICTION TO JURISDICTION.
    </paragraph>

    <heading> Limitation of Liability </heading>

    <paragraph>
      IN NO EVENT WILL THE ROTKI ENTITIES BE LIABLE TO YOU FOR ANY DIRECT,
      INDIRECT, INCIDENTAL, SPECIAL, CONSEQUENTIAL OR PUNITIVE DAMAGES
      (INCLUDING DAMAGES FOR LOSS OF PROFITS, GOODWILL, OR ANY OTHER INTANGIBLE
      LOSS) ARISING OUT OF OR RELATING TO YOUR ACCESS TO OR USE OF, OR YOUR
      INABILITY TO ACCESS OR USE, THE SERVICE OR ANY MATERIALS OR CONTENT ON THE
      SERVICE, WHETHER BASED ON WARRANTY, CONTRACT, TORT (INCLUDING NEGLIGENCE),
      STATUTE, OR ANY OTHER LEGAL THEORY, AND WHETHER OR NOT ANY ROTKI ENTITY
      HAS BEEN INFORMED OF THE POSSIBILITY OF DAMAGE. FOR THE AVOIDANCE OF
      DOUBT, THE EXCLUDED DAMAGES ALSO INCLUDE WITHOUT LIMITATION, LOSS OF
      SAVINGS OR REVENUE; LOSS OF PROFIT; LOSS OF USE; LOSS OF BUSINESS, LOSS OF
      VALUE, THE CLAIMS OF THIRD PARTIES; AND ANY COST OF ANY SUBSTITUTE
      EQUIPMENT OR SERVICES. IF ROTKI CANNOT LAWFULLY DISCLAIM LIABILITY FOR ANY
      OF THE FOREGOING DAMAGES, THEN THE AGGREGATE LIABILITY OF THE ROTKI
      ENTITIES TO YOU FOR ALL CLAIMS ARISING OUT OF OR RELATING TO THE USE OF OR
      ANY INABILITY TO USE ANY PORTION OF THE SERVICE OR OTHERWISE UNDER THESE
      TERMS, WHETHER IN CONTRACT, TORT, OR OTHERWISE, IS LIMITED TO THE GREATER
      OF THE AMOUNTS YOU HAVE PAID TO USE THE SERVICE OR 80€ , TO THE FULLEST
      EXTENT PERMITTED UNDER APPLICABLE LAW.
    </paragraph>

    <paragraph>
      SOME JURISDICTIONS DO NOT ALLOW THE EXCLUSION OR LIMITATION OF LIABILITY
      FOR CONSEQUENTIAL OR INCIDENTAL DAMAGES, IN WHICH CASE SUCH LIMITATIONS
      SHALL APPLY TO YOU TO THE EXTENT PERMITTED IN SUCH JURISDICTION.
      FURTHERMORE, NOTHING IN THESE TERMS LIMITS OR EXCLUDES ANY LIABILITY THAT
      CANNOT BE LIMITED OR EXCLUDED BY LAW, SUCH AS LIABILITY FOR INTENTIONAL
      VIOLATION OF THESE TERMS. NOTHING IN THESE TERMS AFFECTS YOUR LEGAL RIGHTS
      AS A CONSUMER. EACH PROVISION OF THESE TERMS THAT PROVIDES FOR A
      LIMITATION OF LIABILITY, DISCLAIMER OF WARRANTIES, OR EXCLUSION OF DAMAGES
      IS INTENDED TO AND DOES ALLOCATE THE RISKS BETWEEN THE PARTIES UNDER THESE
      TERMS. THIS ALLOCATION IS AN ESSENTIAL ELEMENT OF THE BASIS OF THE BARGAIN
      BETWEEN THE PARTIES. EACH OF THESE PROVISIONS IS SEVERABLE AND INDEPENDENT
      OF ALL OTHER PROVISIONS OF THESE TERMS. THE LIMITATIONS IN THIS SECTION
      WILL APPLY EVEN IF ANY LIMITED REMEDY FAILS OF ITS ESSENTIAL PURPOSE.
    </paragraph>

    <heading> Force Majeure </heading>

    <paragraph>
      Rotki will be excused from performance under these Terms for any period
      that it is prevented from or delayed in performing any obligations
      pursuant to these Terms, in whole or in part, as a result of a Force
      Majeure Event. To the fullest extent permitted under applicable law, for
      purposes of this section, “Force Majeure Event” means an event or series
      of events caused by or resulting from any of the following: (1) weather
      conditions or other elements of nature or acts of God; (2) acts of war,
      acts of terrorism, insurrection, riots, civil disorders or rebellion; (3)
      quarantines or embargoes, (4) labor strikes; (4) telecommunications,
      network, computer, server or Internet downtime; (5) unauthorized access to
      Rotki information technology systems by third parties; or (6) other causes
      beyond the reasonable control of Rotki.
    </paragraph>

    <heading> Governing Law and Competent Courts </heading>

    <paragraph>
      To the fullest extent permitted pursuant to applicable law, these Terms
      are governed by the laws of the State of Berlin -- Germany without regard
      to conflict of law principles. If a lawsuit or court proceeding is
      permitted under these Terms, then you and Rotki agree to submit to the
      personal and exclusive jurisdiction of the state courts located in Berlin,
      Germany for the purpose of litigating any dispute. We operate the Service
      from our offices in Germany, and we make no representation that Materials
      included in the Service are appropriate or available for use in other
      locations.
    </paragraph>
  </page>
</template>

<script lang="ts">
import { defineComponent } from '@nuxtjs/composition-api'

export default defineComponent({
  name: 'TermsOfService',
})
</script>

<style lang="scss" module>
@import '~assets/css/media.scss';
@import '~assets/css/main.scss';

.list {
  list-style-type: decimal;
  padding-left: $mobile-margin * 2;
  color: #808080;
}
</style>
