import {
  RiAppleLine,
  RiArrowDropRightLine,
  RiArrowLeftLine,
  RiArrowRightLine,
  RiBankLine,
  RiCalendarTodoLine,
  RiChatSmile2Line,
  RiCloseLine,
  RiDiscordLine,
  RiDownloadCloud2Line,
  RiExternalLinkLine,
  RiGithubLine,
  RiHandCoinLine,
  RiLightbulbLine,
  RiLogoutBoxRLine,
  RiMailSendLine,
  RiMenuLine,
  RiMoneyDollarCircleLine,
  RiTimer2Line,
  RiTwitterXLine,
  RiUserLocationLine,
  RiWindowsLine,
  RuiPlugin,
} from '@rotki/ui-library';
import { defineNuxtPlugin } from '#app';
import '@fontsource/roboto/latin.css';

export default defineNuxtPlugin((nuxtApp) => {
  nuxtApp.vueApp.use(RuiPlugin, {
    mode: 'light',
    icons: [
      RiAppleLine,
      RiArrowDropRightLine,
      RiArrowLeftLine,
      RiArrowRightLine,
      RiCloseLine,
      RiDiscordLine,
      RiDownloadCloud2Line,
      RiExternalLinkLine,
      RiGithubLine,
      RiLightbulbLine,
      RiLogoutBoxRLine,
      RiMailSendLine,
      RiMenuLine,
      RiTimer2Line,
      RiTwitterXLine,
      RiUserLocationLine,
      RiWindowsLine,
      RiBankLine,
      RiMoneyDollarCircleLine,
      RiCalendarTodoLine,
      RiHandCoinLine,
      RiChatSmile2Line,
    ],
  });
});
